### ISSUE TITLE
Not corrected intercept value

### ISSUE THREAD

**Issue by andreihushcha** [learn-co-curriculum/dsc-linear-transformations-lab#1]
## Link to Canvas

https://github.com/learn-co-curriculum/dsc-linear-transformations-lab

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

### Source

```
Negative \$17k for a home with zeros across the board...what does that mean?
```

### Concern

Should be $ 170k, instead of 17
![image](https://github.com/learn-co-curriculum/dsc-linear-transformations-lab/assets/117996551/fb808776-6786-4d21-af79-7d94f860c0fd)

## What OS Are You Using?

- [ ] OS X
- [ x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
We're taking a look. Thank you for raising this issue.

**Comment by bpurdy-ds** [comment]
@andreihushcha, may you please drop in the Canvas link as well to this page? Thank you.

**Comment by bpurdy-ds** [comment]
@andreihushcha I have ran through our code and then ran through your code snippet, and I'm getting the same answers, i.e. the differences with the slope and standard error. You can send us your complete code, and please also reach out to your instructor, if you have not already done so. This may be something that your instructor can more easily troubleshoot than us via GH. Thanks again.

**Comment by bpurdy-ds** [comment]
I am going to close this, but reopen if you are still having this issue after reaching out to your instructor.
